# Generated by Django 5.2.3 on 2025-07-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawphotoupload',
            name='s3_key',
            field=models.CharField(blank=True, help_text='S3 object key for direct uploads', max_length=500, null=True),
        ),
    ]
